// ===========================================================================
// PERMANENT SITE CONTENT — generated by the admin panel
// Paste this ENTIRE block over the contents of lib/site-data.ts, then rebuild.
// ===========================================================================

import type { SiteContent } from "./types";

export const siteData: SiteContent = {
  "hero": {
    "brand": "ANIK AI LABS",
    "tagline": "Building AI Solutions That Solve Real Problems",
    "description": "Custom software, AI automation, business dashboards, retail systems and data analytics — designed and built to ship.",
    "primaryCta": "View Projects",
    "secondaryCta": "Ask Developer"
  },
  "about": {
    "founderName": "Anik Sahoo",
    "aboutText": "I'm a student developer and AI/software builder behind ANIK AI LABS. I design and ship tools that people actually use. My focus is practical AI, automation, business tools, data analytics, and real-world software systems — products that solve concrete problems for shops, teams, and individuals, not just demos.",
    "photoUrl": "https://cdn.corenexis.com/f/hn6VFXShio1.png",
    "skills": [
      "Practical AI",
      "Automation",
      "Business Tools",
      "Data Analytics",
      "Real-World Systems"
    ]
  },
  "projects": [
    {
      "slug": "filemind",
      "name": "FileMind",
      "tagline": "AI-powered laptop command center",
      "description": "A desktop command center that lets you search files, launch apps, and run voice commands — supercharged with local AI and project memory, all behind a read-only safety layer.",
      "image": "https://cdn.corenexis.com/f/IT4AzcCQsef.png",
      "video": "",
      "stack": [
        "Python",
        "Local LLM",
        "Speech-to-Text",
        "Electron"
      ],
      "features": [
        "Instant file search",
        "App launcher",
        "Voice commands",
        "Project memory",
        "Local AI integration",
        "Read-only safety"
      ],
      "liveUrl": "",
      "githubUrl": "",
      "askCta": "Ask",
      "accent": "from-teal-glow to-cyan-glow"
    },
    {
      "slug": "nandarani-pos",
      "name": "Nandarani POS",
      "tagline": "Retail billing & inventory system",
      "description": "A complete retail point-of-sale and inventory platform with barcode and GST billing, purchase entry, stock transfer, customer dues, QR payments, and rich sales analytics.",
      "image": "https://cdn.corenexis.com/f/BuVkHPTVtbb.png",
      "video": "",
      "stack": [
        "React",
        "Node.js",
        "SQLite",
        "Electron"
      ],
      "features": [
        "Barcode billing",
        "GST billing",
        "Purchase entry",
        "Stock transfer",
        "Customer due management",
        "QR payment support",
        "Sales analytics"
      ],
      "liveUrl": "",
      "githubUrl": "",
      "askCta": "Ask",
      "accent": "from-cyan-glow to-blue-400"
    },
    {
      "slug": "nandarani-catalog",
      "name": "Nandarani Catalog",
      "tagline": "Digital product catalog website",
      "description": "A mobile-first digital catalog that showcases products beautifully, with QR sharing, shop details, and one-tap WhatsApp inquiry to turn browsers into buyers.",
      "image": "https://cdn.corenexis.com/f/x8lJBO5T2or.png",
      "video": "",
      "stack": [
        "Next.js",
        "Tailwind CSS",
        "WhatsApp API"
      ],
      "features": [
        "Product showcase",
        "QR sharing",
        "Shop details",
        "WhatsApp inquiry",
        "Mobile-first browsing"
      ],
      "liveUrl": "",
      "githubUrl": "",
      "askCta": "Ask",
      "accent": "from-emerald-400 to-teal-glow"
    },
    {
      "slug": "ai-data-detective",
      "name": "AI Data Detective",
      "tagline": "AI data cleaning & analytics",
      "description": "An AI-driven analytics tool that cleans messy data, surfaces business insights on a KPI dashboard, and auto-generates executive summaries and reports.",
      "image": "https://cdn.corenexis.com/f/xucFIMuOabn.png",
      "video": "",
      "stack": [
        "Python",
        "Pandas",
        "LLM",
        "Streamlit"
      ],
      "features": [
        "Automated data cleaning",
        "KPI dashboard",
        "Business insights",
        "Automated reports",
        "Executive summary generation"
      ],
      "liveUrl": "",
      "githubUrl": "",
      "askCta": "Ask",
      "accent": "from-violet-400 to-cyan-glow"
    }
  ],
  "gallery": [
    {
      "id": "g-filemind",
      "url": "https://cdn.corenexis.com/f/IT4AzcCQsef.png",
      "title": "FileMind",
      "description": "AI-powered laptop command center"
    },
    {
      "id": "g-pos",
      "url": "https://cdn.corenexis.com/f/BuVkHPTVtbb.png",
      "title": "Nandarani POS",
      "description": "Retail billing & inventory system"
    },
    {
      "id": "g-catalog",
      "url": "https://cdn.corenexis.com/f/x8lJBO5T2or.png",
      "title": "Nandarani Catalog",
      "description": "Digital product catalog website"
    },
    {
      "id": "g-detective",
      "url": "https://cdn.corenexis.com/f/xucFIMuOabn.png",
      "title": "AI Data Detective",
      "description": "AI data cleaning & analytics"
    }
  ],
  "services": [
    {
      "id": "s-custom",
      "title": "Custom Software Development",
      "description": "Tailored applications built around your exact workflow — from desktop tools to full web platforms.",
      "icon": "Boxes"
    },
    {
      "id": "s-ai",
      "title": "AI Automation",
      "description": "Put AI to work on repetitive tasks: lead handling, document processing, and smart assistants.",
      "icon": "BrainCircuit"
    },
    {
      "id": "s-dash",
      "title": "Business Dashboard Development",
      "description": "Real-time KPI dashboards that turn raw numbers into decisions you can act on.",
      "icon": "LayoutDashboard"
    },
    {
      "id": "s-retail",
      "title": "Retail Software Systems",
      "description": "Billing, inventory, and POS systems designed for real shops and real margins.",
      "icon": "Store"
    },
    {
      "id": "s-data",
      "title": "Data Analytics & Reporting",
      "description": "Clean data, clear insights, and automated reports that write themselves.",
      "icon": "LineChart"
    },
    {
      "id": "s-web",
      "title": "Website Development",
      "description": "Fast, modern, mobile-first websites that look premium and convert visitors.",
      "icon": "Globe"
    },
    {
      "id": "s-n8n",
      "title": "n8n Workflow Automation",
      "description": "Connect your tools into automated pipelines — leads, notifications, CRMs, and beyond.",
      "icon": "Workflow"
    }
  ],
  "contact": {
    "email": "your-email@example.com",
    "whatsapp": "+91 00000 00000",
    "github": "https://github.com/your-username",
    "linkedin": "https://linkedin.com/in/your-username",
    "instagram": "https://instagram.com/your-username"
  },
  "media": {
    "productPhotos": [],
    "promoVideos": [],
    "brandBookPdf": "https://drive.google.com/file/d/1Mqmlyjqtmne2SdEMzoCo6EBNQk9DXUiy/view?usp=sharing",
    "resumePdf": ""
  },
  "assistant": {
    "title": "AI Assistant for Project Queries",
    "description": "Chat with the ANIK AI LABS assistant to explore projects, ask about services, discuss requirements, and connect with the developer.",
    "telegramUrl": "",
    "status": "coming-soon",
    "ctaText": "Chat with AI Assistant",
    "flowSteps": [
      "Open AI Assistant",
      "Choose Project / Service / Hire Developer",
      "If Hire Developer is selected, WhatsApp contact is shared",
      "Continue discussion directly"
    ],
    "hireWhatsappUrl": "",
    "whatsappRevealCondition": "Hire Developer"
  },
  "videoShowcase": {
    "sectionTitle": "Promotional Video Showcase",
    "sectionDescription": "Watch the ANIK AI LABS project launch film featuring FileMind, Nandarani POS, Smart Catalog Platform, and AI Data Detective.",
    "videoTitle": "ANIK AI LABS — Project Launch Film",
    "videoDescription": "A cinematic walkthrough of the products built by ANIK AI LABS.",
    "thumbnailUrl": "https://cdn.corenexis.com/f/rcwNT3MRMGh.png",
    "videoUrl": "https://videotourl.com/videos/1782111053627-cf4b717d-85cc-4d66-b16c-759b2eb79034.mp4",
    "projectTag": "Showcase",
    "duration": "",
    "status": "active"
  },
  "cmo": {
    "title": "AI CMO Dashboard",
    "subtitle": "Powered by AI Marketing Automation",
    "description": "This dashboard displays content automatically generated by the ANIK AI LABS AI CMO system including SEO research, blog content, social media posts, and marketing assets.",
    "status": "active",
    "googleSheetUrl": "",
    "googleSheetCsvUrl": "",
    "refreshInterval": 60,
    "refreshSeconds": 60,
    "apiEnabled": true,
    "webhookSecret": "",
    "enableAutoRefresh": true,
    "enablePublic": true,
    "enableStatistics": true,
    "enableFeed": true,
    "items": [
      {
        "id": "cmo-1",
        "keyword": "AI automation for small business",
        "blog_title": "How AI Automation Saves Small Businesses 20+ Hours Every Week",
        "meta_title": "AI Automation for Small Business | ANIK AI LABS",
        "meta_description": "Discover how AI automation streamlines billing, lead handling and reporting so small businesses reclaim 20+ hours a week and grow faster.",
        "blog": "Small businesses lose countless hours to repetitive tasks: manual billing, chasing leads, copying data between tools, and writing the same reports every week. AI automation changes that. By connecting your tools into a single automated pipeline, routine work runs itself in the background. At ANIK AI LABS we build automations that capture leads, qualify them with AI, log them to a CRM, and notify you instantly. The result is a leaner operation where your team focuses on customers instead of busywork. Start small with one workflow, measure the time saved, then expand. Within weeks most businesses recover a full working day every week.",
        "instagram_caption": "Stop doing work a robot can do. ⚙️ AI automation just gave this business 20+ hours back every week. #AIAutomation #SmallBusiness #ANIKAILABS",
        "linkedin_post": "Most small businesses don't have a time problem — they have an automation gap. We helped a client move billing, lead capture and reporting onto an AI-driven pipeline and they reclaimed 20+ hours a week. Here's the framework we used to get there.",
        "generated_date": "2026-06-20"
      },
      {
        "id": "cmo-2",
        "keyword": "retail POS billing software",
        "blog_title": "Choosing Retail POS Billing Software That Actually Grows Sales",
        "meta_title": "Retail POS Billing Software Guide | ANIK AI LABS",
        "meta_description": "A practical guide to picking retail POS billing software with barcode, GST, inventory and analytics that helps shops bill faster and sell more.",
        "blog": "The right point-of-sale system does more than print bills — it becomes the nerve center of your shop. Look for barcode and GST billing to speed up checkout, purchase entry and stock transfer to keep inventory accurate, and customer due management to protect cash flow. The real edge, though, is analytics: knowing your best-sellers, slow movers and peak hours lets you stock smarter and run promotions that work. Nandarani POS was built around exactly these needs for real shops with real margins. When billing, inventory and insight live in one place, every checkout becomes a data point that helps you grow.",
        "instagram_caption": "Faster billing. Smarter stock. Happier customers. 🛒 The POS upgrade your shop deserves. #RetailPOS #BillingSoftware #ANIKAILABS",
        "linkedin_post": "Retail billing software shouldn't just process sales — it should reveal them. The shops that win track best-sellers, dead stock and peak hours automatically. Here's what to look for when choosing a POS in 2026.",
        "generated_date": "2026-06-18"
      },
      {
        "id": "cmo-3",
        "keyword": "business analytics dashboard",
        "blog_title": "From Messy Spreadsheets to a Business Analytics Dashboard in a Day",
        "meta_title": "Business Analytics Dashboard | ANIK AI LABS",
        "meta_description": "Turn messy spreadsheets into a clean KPI dashboard with AI-driven cleaning, insights and automated executive summaries.",
        "blog": "Data is only useful when you can see it clearly. Most businesses sit on spreadsheets full of insight they never act on because the numbers are messy and scattered. AI Data Detective cleans that data automatically, surfaces the KPIs that matter, and generates an executive summary in plain language. Instead of spending a day wrangling rows, you open a dashboard that already tells the story: what's growing, what's stalling, and where to look next. Clean data plus clear visuals plus automated narrative equals decisions you can make in minutes, not weeks.",
        "instagram_caption": "Your data is trying to tell you something. 📊 Let AI translate it into decisions. #DataAnalytics #Dashboard #ANIKAILABS",
        "linkedin_post": "Dashboards don't fail because of bad charts — they fail because of dirty data. We automated cleaning, KPI selection and executive summaries so the dashboard does the thinking. Here's the approach.",
        "generated_date": "2026-06-15"
      }
    ]
  }
};
